print("=====================")
print("Server Information")
print("=====================")
print("Hostname: app01")
print("OS: RHEL 9.7")
print("Role: Application Server")
print("CPU: 8")
print("Memory: 16 GB")
print("Enviroment: LAB\n==========================")
